# Default values for rimori-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.rimori.se/study/rimori
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.3.0"

uploaderImage:
  repository: registry.rimori.se/study/rimori-pdf-converter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.3.0"

rimoriApp:
  enabled: true  # Set to false to disable rimori-app

converter:
  enabled: true  # Set to false to disable converter
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

env:
  NEXT_PUBLIC_SUPABASE_URL: https://bznvqlkxankwapnodhek.supabase.co
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ""
  NEXT_PUBLIC_OPENAI_API_KEY: ""
  NEXT_PUBLIC_ANTHROPIC_API_KEY: ""
  NEXT_PUBLIC_LOGGING_BACKEND_URL: https://logging.rimori.se
  NEXT_PUBLIC_LOGGING_USERNAME: admin
  NEXT_PUBLIC_LOGGING_PASSWORD: ""
  NEXT_PUBLIC_ALLOWED_DOMAINS: ""
  NEXT_PUBLIC_ELEVENLABS_API_KEY: ""
  NEXT_PUBLIC_MATOMO_URL: https://matomo.rimori.se
  NEXT_PUBLIC_UPLOAD_BACKEND: https://upload.rimori.se/upload
  OPENAI_API_KEY: ""
  FRONTEND_DOMAIN: https://study.rimori.se
  
service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "traefik"
  annotations: 
    "cert-manager.io/cluster-issuer": letsencrypt-production
  hosts:
    - host: rimori.rimori.se
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: rimori-tls
     hosts:
       - rimori.rimori.se

uploaderIngress:
  enabled: true
  className: "traefik"
  annotations: 
    "cert-manager.io/cluster-issuer": letsencrypt-production
  hosts:
    - host: upload.rimori.se
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: rimori-uploader-tls
     hosts:
       - upload.rimori.se

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
