# kubectl create secret docker-registry rimori-registry \
# --docker-server=https://registry.rimori.se \
# --docker-username=robot_rimori-cluster-7 \
# --docker-password=GaPEyJNjR3nTuYPIxtkCN9Up8Poqimn0 \
# --dry-run=client -o yaml


apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LnJpbW9yaS5zZSI6eyJ1c2VybmFtZSI6InJvYm90X3JpbW9yaS1jbHVzdGVyLTciLCJwYXNzd29yZCI6IkdhUEV5Sk5qUjNuVHVZUEl4dGtDTjlVcDhQb3FpbW4wIiwiYXV0aCI6ImNtOWliM1JmY21sdGIzSnBMV05zZFhOMFpYSXROenBIWVZCRmVVcE9hbEl6YmxSMVdWQkplSFJyUTA0NVZYQTRVRzl4YVcxdU1BPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: rimori-registry
  namespace: rimori
type: kubernetes.io/dockerconfigjson
