# kubectl create secret docker-registry rimori-registry \
# --docker-server=https://registry.rimori.se \
# --docker-username=your_user \
# --docker-password=your_password \
# --dry-run=client -o yaml


apiVersion: v1
data:
  .dockerconfigjson: the_resulting_json # change
kind: Secret
metadata:
  creationTimestamp: null
  name: rimori-registry
  namespace: rimori
type: kubernetes.io/dockerconfigjson
